export default {
  ITEM_INIT: 'ITEM_INIT',
  ITEM_ADD: 'ITEM_ADD',
  ITEM_SAVE: 'ITEM_SAVE',
  ITEM_TOGGLE: 'ITEM_TOGGLE',
  ITEM_TOGGLE_ALL: 'ITEM_TOGGLE_ALL',
  ITEM_DELETE: 'ITEM_DELETE',
  ITEM_DELETE_COMPLETED: 'ITEM_DELETE_COMPLETED',
};